version: "3.8"
services:
    tipjar:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tipjar-app
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production
        volumes:
            - .:/app
            - ./env:/app/env
        restart: unless-stopped
        depends_on:
            # - hydra-node
            # - cardano-node
            # - env

    # hydra-node:
    #     image: inputoutput/hydra-node:latest
    #     container_name: hydra-node
    #     ports:
    #         - "4001:4001"
    #     environment:
    #         # HYDRA_NODE_ENV: production
    #     volumes:
    #         - ./env:/hydra/env
    #     restart: unless-stopped

    # cardano-node:
    #     image: inputoutput/cardano-node:latest
    #     container_name: cardano-node
    #     ports:
    #         - "3001:3001"
    #     environment:
    #         # CARDANO_NODE_ENV: production
    #     volumes:
    #         - ./env:/cardano/env
    #     restart: unless-stopped
